[package]
name = "some_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
some_other_lib = { path = "../some_other_lib" }
